### ISSUE TITLE
Rainy Days as part of Data Products

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#529]
Rainy Days data products need to be added on the list of products because some users are interested not only with the amounts of rain but also with the numbers of rainy days in a particular month of year.

**Comment by smachua** [comment]
@mhabimana, I will work on it.

**Comment by smachua** [comment]
@mhabimana, resolved through PR #613

**Comment by mhabimana** [comment]
This can now be closed.

**Comment by Iyakaremyevedaste** [comment]
@smachua thanks for adding rainy days as part of the data products. I still need some clarification on how the algorithm works. For example, climatologically, we define a rainy day as any day recorded >=1mm. The threshold we define there takes what sign (>=, >, etc.)? If it's possible, a sign option can be added. Thanks for the improvements being done in our DB
