### ISSUE TITLE
Improvement required on Data entry Forms

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#556]
In the current implementation of Data entry forms,it is not possible to select specific stations,elements and period time range to upload into the observationinitial. I have a case of Meteo Rwanda,they are using Climsoft at the outstations and observers here are entering data directly into the  server at HQ since all the stations have got internet and are connected to the server,pointing to the server database. The issue here is that Data manager would wish to upload specific stations data and elements into the  observationinitial assuming other stations are already existing in the database or are not yet ready to be uploaded due to some reasons. 
Meteo Rwanda team is suggesting  to implement another dialog when the upload button  is clicked where user may specify the stations,elements,time period of data to be transferred into observationinitial, a similar dialog to  the QC dialog below can be used for this purpose:
![image](https://user-images.githubusercontent.com/10340170/63413459-68e00000-c402-11e9-8af0-b8ad0ab1850a.png)

**Comment by Patowhiz** [comment]
I can do this

**Comment by mhabimana** [comment]
@Patowhiz 👍 that great.

**Comment by Iyakaremyevedaste** [comment]
@Patowhiz how far ? We are currently receiving huge data in forms on daily basis. That option is highly needed for us to easily load data in obsinitial and perform QC as well.  Please we urgently need that option.  Thank you

**Comment by Patowhiz** [comment]
This will be available in the next release.
@mhabimana what's your suggestion on the new form design? I think we will have to bring on board @smachua

**Comment by mhabimana** [comment]
@Patowhiz : I don't think the design will change but my view is when the **upload** button is clicked it will open a dialog like the one below where user specify the stations,elements and the range  of data to be uploaded into observationinitial instead of upload all the data in the form including what were already existing in the observationinitial:
![image](https://user-images.githubusercontent.com/10340170/63413459-68e00000-c402-11e9-8af0-b8ad0ab1850a.png)

**Comment by smachua** [comment]
I agree with @mhabimana but the dialog to use for selecting stations, elements and period should be designed like this:

![image](https://user-images.githubusercontent.com/12034121/64550031-ad442900-d33a-11e9-8783-e7e96ea2454f.png)

**Comment by mhabimana** [comment]
It was noted in yesterday's meeting that further discussion on the implementation of this option need to  continue until the final decision. Therefore,I call upon all of you to continue further discussion on this issue here instead of creating a new issue.

**Comment by smachua** [comment]
I intend to resolve this issue by improving the upload dialog to enable users select records they wish to upload. In particular INAM expressed great need for such functionality in their current data digitization project.

**Comment by mhabimana** [comment]
This has been implemented successfully and currently working well.
