### ISSUE TITLE
Capturing Future date data

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#569]
@Patowhiz : All data entry forms were set to not allow entering data for future dates sometimes back but it seems this is not working at the moment. Can you please check this?

**Comment by mhabimana** [comment]
@Patowhiz :I think the data forms in the dev branch merged recently were behind the fdata entry forms in the master because some of the features like the function to prevent capturing future date data got lost but if you look at the released v4.1.4 this is working well. I don't really understand what went wrong.

**Comment by Patowhiz** [comment]
This has been fixed with the last changes. Could you kindly test the mergings we made

**Comment by smachua** [comment]
@Patowhiz thanks. We're going to test it then update you. But you may consider uploading of 'Period' values in form_daily2 if you haven't.

**Comment by mhabimana** [comment]
@Patowhiz - saving period values is not yet done on Daily2 form

**Comment by mhabimana** [comment]
@Patowhiz -This need your attention and review. saving period values is not yet done on Daily2 form. and Hourly form.  After typing and saving this, when view in the table (table view) ,you find the period cell is empty.

**Comment by Patowhiz** [comment]
@mhabimana it was an event that was not being raised. I have fixed this

**Comment by mhabimana** [comment]
@Patowhiz - Thanks, period values are now being saved,so this can now be closed.
