### ISSUE TITLE
Mixed up wind data and flag- Form hourlywind

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#570]
@Patowhiz : as I mentioned earlier, data and flags are mixed up in the database table for this form hourlywind (see below): The first text box (ddff) column is how I have entered data in the form and the red color is how data were stored in the database:As you can see,some values for ff are stored in flag and vice-versa
![image](https://user-images.githubusercontent.com/10340170/64536615-123f5500-d322-11e9-8e6f-94803886409c.png)

**Comment by Patowhiz** [comment]
@mhabimana was this solved?

**Comment by mhabimana** [comment]
@Patowhiz -Thanks, This was solved partially because though missing values(M) are present in the form hourly wind table,they are not being transferred into the observationinitial table during the upload process. I will close this issue once you solve this. On all the data entry forms,Missing value(M) should not be skipped during the upload process but should be transferred as well in the observationinitial like other values.

**Comment by smachua** [comment]
@mhabimana I can deal with this issue of uploading data from forms. I will work it out together with the pending issue #533 where you requested if uploading can be done on some selected records. Both issues are somehow related.

**Comment by mhabimana** [comment]
@smachua 👍,noted.

**Comment by Fortunata** [comment]
I am reporting on the issue of limits on the key entry form but I dont know its number. When lower and upper limits are set then during key entry  the value above the limit is encountered and then confirmed by the data entrants that it is a true value V4 Climsoft does not allow it to pass as it was in earlier version. This slows down the work practically because the data manager has to sstop the process to put in unrealistic limits which Will allow those values to pass.

**Comment by smachua** [comment]
@Fortunata you're right. The values that exceeds the limits on key entry are not always wrong and should not stop any operation including uploading the data from the form. That has always been the practice. 

@Patowhiz note that all that is required is a message and flagging them with a different color for attention. NOT stopping anything.

**Comment by Patowhiz** [comment]
@Fortunata @mhabimana I wasn't aware of this. We intentionally disabled data that does not pass all the validations. So basically what you are saying is, data that is beyond it's upper or lower limit is not necessarily wrong data? If that's the case then it's understandable. We will have to change the validation process to counter this

**Comment by mhabimana** [comment]
@Patowhiz - You are right. But the message and the flag colours should be there to prompt data clerks to re-check again this value and correct if possible before validation.

**Comment by Patowhiz** [comment]
@mhabimana this has been solved in PR #616

**Comment by smachua** [comment]
@mhabimana will review and give an update.

**Comment by mhabimana** [comment]
@Patowhiz -This is working well and can now be closed.
