### ISSUE TITLE
New Home 🎉

### ISSUE THREAD

**Issue by isedwards** [climsoft/Climsoft#582]
@opencdms/climsoft
@bruban

When the Climsoft code was first added to GitHub.com in 2015, the `climsoft` name was not available to register.

Therefore we added the repository to the `github.com/opencdms` organisation instead.

Last week, GitHub released the `climsoft` name because it had never been used. We have now registered it for the project.

We're intending to move Climsoft to this new home and allow the `opencdms` space to be used exclusively for OpenCDMS development.

GitHub will forward old links to the new location, so I believe that Visual Studio will continue to work with the repository settings that you already have set up. Links to the Climsoft wiki and other web resources will also be forwarded and therefore continue to work.

I'll perform the transfer this weekend and let you all know when it has been successful.

**Comment by isedwards** [comment]
Climsoft has now moved from `opencdms/Climsoft` to `climsoft/Climsoft` on GitHub.

Everything should continue to work, with all links being forwarded, but let me know if you notice any problems.

**Comment by Patowhiz** [comment]
@isedwards I think the climsoft teams didn't move. I can't tag the climsoft teams in the pull requests, I can only tag individuals

**Comment by Patowhiz** [comment]
What I mean is the following tags don't work
@opencdms/climsoft-developers
@climsoft/climsoft-developers
@Climsoft/climsoft-developers

**Comment by isedwards** [comment]
```
**CLIMSOFT CONTRIBUTORS**
  --- Please read ---
```
When Climsoft moved to it's new home at https://github.com/climsoft/Climsoft, GitHub did not automatically enroll people as members of the new `climsoft` organisation.

You should receive an email from GitHub inviting you to join the new organisation.

Could you please check with other developers that they have managed to join and let us know if there are any problems.

**Comment by Patowhiz** [comment]
I got the invite from you. I managed to join.
