### ISSUE TITLE
Hourly Wind Date Entry Form

### ISSUE THREAD

**Issue by Patowhiz** [climsoft/Climsoft#589]
As mentioned in issue #574.

> • Entries not matching with their respective fields in the underlying table. Some values are
> saved in Flag fields and all flags are saved in Values fields.
> • Error on Uploading - (Error Authentication to host 'localhost' for user 'root' using method
> 'mysql_native_password' failed with message: Access denied for user 'root'@'localhost'
> (using password: NO)).

This form needs the bugs to be  fixed

**Comment by mhabimana** [comment]
@Patowhiz - There is still some issues here because: wind Direction(dd) correspond to 112 in the underlying table and wind speed(ff) correspond to 111. Can you please adjust accordingly? Missing values are suppose to match with ddFlag.

**Comment by Patowhiz** [comment]
Thank you @mhabimana . That was indeed a serious bug in code

**Comment by mhabimana** [comment]
@Patowhiz 👍 It is now working well
