### ISSUE TITLE
Upper and  Lower Limits problem

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#596]
Discussions on the Limits raised by @Fortunata under issue #570 can continue here.

**Comment by mhabimana** [comment]
@smachua : was this issue solved? you mentioned in #570 that you will address it.

**Comment by smachua** [comment]
@mhabimana the #533 was being addressed by @Patowhiz unless you want to take it up. #570  has been resolved.

**Comment by mhabimana** [comment]
@smachua, - Any progress on this issue of allowing reasonable values above or below the limits to sail in?

**Comment by mhabimana** [comment]
@Patowhiz - Are you doing something on the Data entry forms? or you have exhausted all the issues raised.

**Comment by mhabimana** [comment]
This issue need more attention to make sure,data entry operators are not restricted to enter data which are acceptable. I am suggesting that a warning message and the colour should be clear enough to attract the attention  of the data entry operators that the value being entered is above or below the limit set by the administrator before accepting this and if he/she is sure that particular data is correct before accepting this. In this way,the person entering data will check and confirm the value being entered.

**Comment by Steve-Palmer** [comment]
Perhaps I am being cynical about the dedication of data entry operators, but I suggest that entries outside the limits set by the administrator must at least require a second click - e.g. a dialogue which says "The form you are entering contains values outside the range set by the metadata manager. Are you sure the values you have entered are correct?" 
Also ideally keying YES should generate a message to the manager. This will prompt the manager to investigate - 3 options, there is a new record, the limits are wrong, or there is an error in the original form or keying.
I worrry that if casual staff are employed to do data entry, they will type anything just to get paid for the keystrokes. This was a major problem in Sierra Leone, and about 1/3 of the data keyed is probably corrupt.

**Comment by mhabimana** [comment]
@Patowhiz :This issue is still pending and need your attention.
The current situation is that once a value entered via the data entry forms is above or below the limit set in the system by the system administrator or database manager (under metadata element), this can not be accepted  by the system and the person entering data get stuck and can not move forward unless the limits are changed first by the administrator. The new suggestion is to show that the value entered is below or above the limit via message box to warn the data entry clerk to check well on the register but accept this value though below or above the limit to allow the person entering data to move forward instead of stopping him /her to continue entering that data. During the second QC process all values below or above the limit will be detected again and the QC staff/or database admin will decide whether to accept these values or to reject these.

**Comment by mhabimana** [comment]
@Patowhiz - Have you got the chance to look at this.

**Comment by Patowhiz** [comment]
@mhabimana this has been solved in PR #616

**Comment by mhabimana** [comment]
@Patowhiz -Thanks for addressing this issue,I can see the values higher/lower that the limit being coloured,this is great but there is no warning message ( this can be a message box) which is also very important to attract the attention of the key entry operator.

**Comment by Patowhiz** [comment]
Pushed new changes in regards to this

**Comment by mhabimana** [comment]
@Patowhiz -Thanks,I have seen the message box but when clicked at the **OK** button (message box, with the enter Key, the cursor should move to the next text box because most of the data entry don't use the mouse,only the enter key to move faster from a text box to anther.

**Comment by Patowhiz** [comment]
@mhabimana that's now fixed in my last commit. The message will pop up explaining the limits violations and the cursor will move to the control. Please test this on your side

**Comment by mhabimana** [comment]
@Patowhiz -Thanks,this is now working well.
