### ISSUE TITLE
Daily data duplication

### ISSUE THREAD

**Issue by fmucyo** [climsoft/Climsoft#610]
Dear Team,

We are facing an issue with daily rainfall data. The observed data seems to be doubling and I was wondering whether when different users upload the same data from observationinitial to observationfinal, can they be duplicated or doubling?. What could be the reason? This is also making monthly values to double compared to the observed data. kindly see the attached file for your consideration. 
[file of errors.xlsx](https://github.com/climsoft/Climsoft/files/4244002/file.of.errors.xlsx)
?

**Comment by mhabimana** [comment]
@fmucyo - Thanks for your post.We are going to investigate and come back to you very soon.

**Comment by smachua** [comment]
@mhabimana an had found that you are using the same element code for daily total rainfall and hourly total rainfall hence the d

**Comment by fmucyo** [comment]
@smachua this has been solved. we managed to separate them but the issue is on daily data that seem to be doubling when extracted. that is where we need assistance

**Comment by smachua** [comment]
@mhabimana is going to organize an online discussion so that the issue can be fully resolved.

**Comment by fmucyo** [comment]
Thank you!
