### ISSUE TITLE
Enhancement of data selection dialog under Climate Products

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#613]
![image](https://user-images.githubusercontent.com/10340170/80488414-f64afb00-8966-11ea-9819-cdcd71ab93d1.png)
The above dialog need enhancement to enable users to query data very quickly using this dialog. Currently the drop down list is used to select stations and elements one at time, the proposed change is to enable as well selection of station and element using their code, alternatively, list all the stations and elements on the dialog and provides a tick box for quick selection before the station ID (Name)  and element ID (Name) similar to the QC dialog below:
![image](https://user-images.githubusercontent.com/10340170/80490053-75d9c980-8969-11ea-8499-be4a893a008e.png)
@mwaurahk and @Iyakaremyevedaste raised this concern as well.

**Comment by smachua** [comment]
@mhabimana, I will work on it to allow selection of stations and elements by typing station ID and element ID respectively.

**Comment by smachua** [comment]
@mhabimana I will implement it in a way that Stations and Elements will be selected without doing so much scrolling.

**Comment by mhabimana** [comment]
@smachua 👍 Sounds great.

**Comment by Iyakaremyevedaste** [comment]
@smachua that's great! It will save our time.

**Comment by mwaurahk** [comment]
@mhabimana ,@smachua...this will greatly ease our operations.There's also the inability to calculate rainny days..otherwise thank you for your continued efforts to improve climsoft. Asante.

**Comment by smachua** [comment]
@mhabimana, resolved through PR #614.

**Comment by mhabimana** [comment]
This can now be closed.
