### ISSUE TITLE
Sequencer Daily Form is not looping

### ISSUE THREAD

**Issue by mhabimana** [climsoft/Climsoft#615]
@Patowhiz : In this data entry form, the sequencer is stopping at the last element set in the sequencer list table (in my case at element 17) i.e; when the Add New command is clicked,the next element is called until it reaches at the last element set in the table where it stop completely. This should not suppose to stop but should continue to the first element set in the sequencer table (in my case to element 2) and so on.
![image](https://user-images.githubusercontent.com/10340170/81554955-5773c500-9390-11ea-887c-9d5644f0f1b3.png)

**Comment by Patowhiz** [comment]
Looking into this

**Comment by mhabimana** [comment]
@Patowhiz - OK

**Comment by Patowhiz** [comment]
@mhabimana looking at this closely, I think in our previous discussions we said, when the sequencer reaches the end, it should increment the date. That's what all forms are doing right now. They check if the sequencer has reached the end then they increment the dates if that's so, if not they go to the next element.

What are your thoughts on this? Do you still suggest this to be changed? Is it particularly to just this form or even the other forms?

**Comment by mhabimana** [comment]
@Patowhiz -Thank you for looking at this,You are right but you are missing a small point "The system check if the sequencer has reached the end then they go to the next element and increment the dates". For your case,the system increment starting from the end but for my case,the system go to the first element and increment the date,and so on.

**Comment by Patowhiz** [comment]
@mhabimana thanks for the clarification. This has now been fixed. Please test this and let me know

**Comment by Patowhiz** [comment]
When testing this. Please do the same in the other entry forms. Cause the sequencer affects them too.

**Comment by mhabimana** [comment]
@Patowhiz - This is working well and can now be closed.
