### ISSUE TITLE
French translations

### ISSUE THREAD

**Issue by Patowhiz** [climsoft/Climsoft#690]
The current French translations are just auto translations from C.rowdIn
The approved French translations done by @mhabimana need to be added into the translations database.
Dialogs also need to be refactored to work well with the new French translations

**Comment by Patowhiz** [comment]
Dynamic texts also need to be translated into French.

**Comment by mhabimana** [comment]
@Patowhiz and @dannyparsons : Any progress on this? I need to review the project after the french translation has been applied in the software.
