### ISSUE TITLE
Metadata Management

### ISSUE THREAD

**Issue by leopangae** [climsoft/Climsoft#736]
In my system (windows 10 64 bit), after installing the climsoft application, it runs well but cannot accept decimals in the station Metadata  configuration. When I insert something like 34.234 on latitude, it does not go to the databese but when I insert 34, it goes. 

Please help

**Comment by smachua** [comment]
@leopangae please check if your computer is configured to use dot (.) or comma (,) for decimal point.  You can do that thro Control Panel ->Region -> Additional settings...

**Comment by leopangae** [comment]
Thank you for the reply....it is working

**Comment by Patowhiz** [comment]
Thanks @leopangae. I'll now go ahead and close this issue.
