### ISSUE TITLE
Hourly data entry form to have 2 sequencing option

### ISSUE THREAD

**Issue by Patowhiz** [climsoft/Climsoft#741]
Recently, a user asked for the hourly data entry to sequence either by seq_element or seq_daily_element.

**Comment by mhabimana** [comment]
@Patowhiz: As discussed and agreed, a new data entry form called " **Form_hourly1**": **data for one hour for one element for the whole month will be added to the list of data entry forms**, below is the sample layout. This form will sequence hours:
![image](https://github.com/climsoft/Climsoft/assets/10340170/19b50ba0-f545-4383-8d83-f4d96f33cbe5)
